module.exports = {
    buttons: [{
        type: 0,
        index: 0
    }, {
        type: 0,
        index: 1
    }, {
        type: 0,
        index: 2
    }, {
        type: 0,
        index: 3
    }, {
        type: 0,
        index: 4
    }, {
        type: 0,
        index: 5
    }, {
        type: 0,
        index: 6
    }, {
        type: 0,
        index: 7
    }, {
        type: 0,
        index: 8
    }, {
        type: 0,
        index: 9
    }, {
        type: 0,
        index: 10
    }, {
        type: 0,
        index: 11
    }, {
        type: 0,
        index: 12
    }, {
        type: 0,
        index: 13
    }, {
        type: 0,
        index: 14
    }, {
        type: 0,
        index: 15
    }, {
        type: 0,
        index: 16
    }],
    axes: [{
        type: 1,
        index: 0
    }, {
        type: 1,
        index: 1
    }, {
        type: 1,
        index: 2
    }, {
        type: 1,
        index: 3
    }]
};